### ISSUE TITLE
how to stop worker when timeout detected?

### ISSUE THREAD

**Issue by zgjabs** [Jeffail/tunny#10]
Is there a sample implementation of TunnyInterrupt()? It seems that when timeout, TunnyInterrupt() will be called, but the worker is still running, how to stop it?

**Comment by Jeffail** [comment]
Hey @zgjabs, when you implement `TunnyWorker` with `TunnyInterruptable` you need to build a mechanism within your `TunnyJob` definition that listens for signals from your `TunnyInterrupt` definition. It's up to you how that mechanism should work as it depends on what you are doing within `TunnyJob`.
