### ISSUE TITLE
SendWorkAsync defying the purpose of Tunny?

### ISSUE THREAD

**Issue by rogeralsing** [Jeffail/tunny#13]
I'm on the fence for this line:
https://github.com/Jeffail/tunny/blob/master/tunny.go#L329

That defies the purpose of Tunny, no?
Each call to SendWorkAsync will spin up a new Go routine and block it until the work is done.

What am I missing?

**Comment by Jeffail** [comment]
Hey @rogeralsing, the case for Tunny as a whole is fairly niche. I initially wrote it for dealing with an indeterminable number of goroutines that want to access a number of finite resources greater than 1. The obvious example being HTTP handlers (all on a separate goroutine) wanting to access CPUs.

However, in my over-excitement (these were my first steps into Go) I added those async calls as an unnecessary sugar around spawning routines in a loop. It doesn't solve any particular problem, and in hindsight I think the library as a whole doesn't really fit within the Go ecosystem.

Looking back, I probably should have kept tunny to myself and deleted it soon after. Unfortunately it gets cloned a few dozen times a day, so I'd be breaking projects if I touched the API or deleted the repo at this stage.

**Comment by dkiser** [comment]
@Jeffail what are your thoughts about the comment that this library shouldn't fit within the Go ecosystem?  Just simply a comment supporting Go philosophy of minimizing external dependencies?  Authors should only build what they need using idiomatic primitives like channels and selects?

I'm pretty new to Go, but it seemed like this library was clean and minimal.  I found it after implementing some of the same concepts myself in custom code.
