### ISSUE TITLE
Replacement for SendWorkAsync?

### ISSUE THREAD

**Issue by vmarkovtsev** [Jeffail/tunny#21]
The new `Pool` does not provide a way to submit jobs asynchronously. I need this `ProcessAsync`.

**Comment by Jeffail** [comment]
Hey @vmarkovtsev, depending on how you used the method it ought to be simple enough to do something like this:

``` go
go func() {
    foo := pool.Process(5)
    // Insert here the logic you previously had inside the callback
}()
```

The old Async methods were basically just doing that under the hood.

**Comment by vmarkovtsev** [comment]
Right, this should work for me, thanks.

**Comment by penhauer-xiao** [comment]
@vmarkovtsev     I realize that asynchronous pool, with cache

https://github.com/penhauer-xiao/gpool
