### ISSUE TITLE
Expose len(pool.reqChan)

### ISSUE THREAD

**Issue by mikebaldry** [Jeffail/tunny#22]
Its would be useful to be able to see the number of jobs waiting to be processed. Would you have anything against a PR exposing it as `QueueLength()` ?

**Comment by Jeffail** [comment]
Hey @mikebaldry,

Sorry, this ticket slipped under my radar. Done: https://github.com/Jeffail/tunny/commit/59cfa8fcb19f5acba8db07a0dd3cb2fa7edbc228

**Comment by mikebaldry** [comment]
thank you
