### ISSUE TITLE
Process a pool asynchronously 

### ISSUE THREAD

**Issue by cpapidas** [Jeffail/tunny#23]
After big API changes how we can process a pool asynchronously?

Also what about callback functions?

TIP for author: When you change the lib API you have to respect your users and 
1) don't make brake changes if not necessary
2) keep the same feature as before unless you did some terrible wrong before.
3) if you did the 1 and 2 it's ok but the first thing that you have to do is to create a migration guide!

Please, answer the 2 question above!

**Comment by Jeffail** [comment]
Hey @cpapidas,

Migration guide: https://github.com/Jeffail/tunny/issues/19
For your specific question: https://github.com/Jeffail/tunny/issues/21

**Comment by penhauer-xiao** [comment]
@cpapidas  I realize that asynchronous pool, with cache

https://github.com/penhauer-xiao/gpool
