### ISSUE TITLE
I don't understand 1 moment in new API

### ISSUE THREAD

**Issue by free6k** [Jeffail/tunny#26]
example old
```
for {
  _, err_time := pool.SendWorkTimed(time.Millisecond, func() {
    slog.Log(fmt.Sprintf("%#v", "wait connection"), nil)   
    ln.Accept()
  })

  if err_time != nil {
    slog.Log(fmt.Sprintf("%#v", "timeout"), nil)
    time.Sleep(time.Millisecond)
  }
}
```

example new
```
for {
  _, err_time := pool.ProcessTimed(func() {
    slog.Log(fmt.Sprintf("%#v", "wait connection"), nil)   
    ln.Accept()
  }, time.Millisecond)

  if err_time == tunny.ErrJobTimedOut {
    slog.Log(fmt.Sprintf("%#v", "timeout"), nil)
    time.Sleep(time.Millisecond)
  }
}
```

In old version api the function WorkTimed will wait accept connection
In new version api the function ProcessTimed will throw always timeout error

Where right working?
I used to think what workTimed for wait free goroutine from pool
But new api said for me what procesTimed about timeout for function execute time?

Sorry for my bad english.. Thanks

**Comment by Jeffail** [comment]
Hey @free6k, the old API was odd in that the `time.Duration` you provided in the first call was multiplied by `time.Millisecond` (https://github.com/Jeffail/tunny/blob/452a8e97d6a39fdd8fb5fdf1327eed2bf0c3429c/tunny.go#L239) within the function call, so your timeout would have actually been much higher than one millisecond (the equivalent of `time.Millisecond*time.Millisecond`).

This was obviously odd and broken behaviour and so the new API applies exactly your `time.Duration` without change. If you call the timeout function with something sensible like `pool.ProcessTimed(foo, time.Second*5)` you should notice the call gets make (unless it takes longer than 5 seconds).

**Comment by Digl** [comment]
when I call 
`pool.ProcessTimed(x, time.Second*30)`
and there is currently no free worker available, the timer will start already?
I would have expected the timer to start once the func is actually being called by a worker.
Am I wrong with this assumption?

Thx
