### ISSUE TITLE
doesn't work with 32 bit Windows

### ISSUE THREAD

**Issue by aj3423** [Jeffail/tunny#27]
It's all ok for 64 bit, but if I set `GOARCH=386`, there is a panic. My test code:

	package main

	import (
		"github.com/Jeffail/tunny"
	)

	var pool *tunny.Pool

	func main() {

		pool = tunny.NewFunc(10, func(data interface{}) interface{} {
			str := data.(string)
			println("str:", str)

			return nil
		})
		defer pool.Close()

		pool.Process("11111111")

		for {
		}

	}

And the panic output:

$ go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x401bdc]

goroutine 1 [running]:
runtime/internal/atomic.Xadd64(0x1305801c, 0x1, 0x0, 0x13058014, 0x44c7d4)
        D:/Go/src/runtime/internal/atomic/asm_386.s:102 +0xc
github.com/Jeffail/tunny.(*Pool).Process(0x13058000, 0x459ae0, 0x473168, 0x13046090, 0x13044030)
        d:/gopath/src/github.com/Jeffail/tunny/tunny.go:152 +0x3e
main.main()
        e:/go/3/3.go:19 +0x7f
exit status 2

**Comment by aj3423** [comment]
I found this is 

https://code.google.com/p/go/issues/detail?id=5278

On x86-32, the 64-bit functions use instructions unavailable before the
   Pentium MMX. On both ARM and x86-32, it is the caller's responsibility to
   arrange for 64-bit alignment of 64-bit words accessed atomically. The
   first word in a global variable or in an allocated struct or slice can be
   relied upon to be 64-bit aligned.

Maybe it can be solved by replacing `atomic.AddUint64` with 

    mutex.Lock()
    p.queuedJobs += 1
    mutex.Unlock()

**Comment by Jeffail** [comment]
Hey @aj3423 I think it should be enough to change the position of `queuedJobs` so that its at the top of the struct declaration. Like this:

``` go
type Pool struct {
        queuedJobs int64
	ctor    func() Worker
	workers []*workerWrapper
	reqChan chan workRequest

	workerMut  sync.Mutex
}
```

**Comment by aj3423** [comment]
> 
> ```go
> type Pool struct {
>         queuedJobs int64
> 
> 	ctor    func() Worker
> 	workers []*workerWrapper
> 	reqChan chan workRequest
> 
> 	workerMut  sync.Mutex
> }
> ```

That's it, I tried this on my Win10-64bit with GOARCH=386,  it does not crash anymore.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/tunny/commit/4921fff29480bad359ad2fb3271fb461c8ffe1fc
Released: https://github.com/Jeffail/tunny/releases/tag/0.1.2
