### ISSUE TITLE
Getting the worker id in the job function

### ISSUE THREAD

**Issue by PuKoren** [Jeffail/tunny#28]
Hello ! It would be really helpful to me to get the worker ID in the executed job, because I want to parallelize work using a pool of singletons that are stateful, so one should never process more than 1 task at a time, but I can create X of them.

I was thinking of something like this:
```go
tunny.NewFunc(3, func(payload interface{}, workerId int) interface{} {
    // workerId can be 0, 1, or 2
})
```

Could it be an interesting feature? Can make a PR if you think it have a chance to be included in the project.

====

Edit: Another way would be to be able to provide to tunny our own workers, implementing the tunny worker interface (this way we can expose the required element in the function) - I think it may be a cleaner way to implement it (@naggingant)

What do you suggest ?

**Comment by Jeffail** [comment]
Hey @PuKoren, there's already an API for implementing your own workers: https://godoc.org/github.com/Jeffail/tunny#New, you provide a constructor and Tunny does the rest, that would allow you to manage the workerIds yourself.

**Comment by PuKoren** [comment]
Hello @Jeffail, thanks for your answer, sorry for taking your time. I don't know why I didn't see it on the docs :man_facepalming:
