### ISSUE TITLE
Goroutines and SendWork

### ISSUE THREAD

**Issue by andykillmer** [Jeffail/tunny#9]
Is it advisable to SendWork to a pool from within a goroutine? For example, I have a Go program that creates image thumbnails. Since image resizing in pure Go is not the fastest, I am using this library to resize multiple images at a time.

Here's an oversimplified version of how I'm using this library:
```go
scanner := bufio.NewScanner(os.Stdin)
for scanner.Scan() {
	pathToImage := scanner.Bytes()

	go func() {
		pool.SendWork(pathToImage)
	}()
}
```

Is this the wrong approach?

**Comment by Jeffail** [comment]
Hey @andykillmer, that should work fine. The call to `SendWork` is a blocking call when the pool is at capacity, and therefore it should be run from a separate goroutine.
